// ===== 加密热词数据 =====

const cryptoTermCategories = {
    all:       { label: '全部' },
    defi:      { label: 'DeFi' },
    nft:       { label: 'NFT / 数字藏品' },
    layer2:    { label: 'Layer 2' },
    consensus: { label: '共识 / 安全' },
    trading:   { label: '交易 / 市场' },
    infra:     { label: '基础设施' },
    web3:      { label: 'Web3 / DAO' },
    slang:     { label: '圈内黑话' },
};

const cryptoTerms = [
    // ===== DeFi =====
    {
        word: 'DeFi',
        zh: '去中心化金融',
        category: 'defi',
        difficulty: '初级',
        defEn: 'Decentralized Finance — financial services built on blockchain without traditional intermediaries like banks.',
        defZh: '去中心化金融 — 在区块链上构建的金融服务，无需银行等传统中介机构。',
        example: 'DeFi protocols like Uniswap allow users to trade tokens without a centralized exchange.',
        exampleZh: 'Uniswap 等 DeFi 协议允许用户在无需中心化交易所的情况下交易代币。',
    },
    {
        word: 'Yield Farming',
        zh: '流动性挖矿',
        category: 'defi',
        difficulty: '中级',
        defEn: 'The practice of staking or lending crypto assets to earn returns in the form of additional tokens.',
        defZh: '通过质押或借出加密资产来获取额外代币回报的做法。',
        example: 'She earned 20% APY through yield farming on Aave.',
        exampleZh: '她通过在 Aave 上进行流动性挖矿获得了 20% 的年化收益。',
    },
    {
        word: 'Liquidity Pool',
        zh: '流动性池',
        category: 'defi',
        difficulty: '中级',
        defEn: 'A smart contract holding pairs of tokens that enables decentralized trading and automated market making.',
        defZh: '一种智能合约，持有成对的代币，实现去中心化交易和自动做市。',
        example: 'Providing liquidity to an ETH/USDC pool earns you trading fees.',
        exampleZh: '向 ETH/USDC 池提供流动性可以赚取交易手续费。',
    },
    {
        word: 'Staking',
        zh: '质押',
        category: 'defi',
        difficulty: '初级',
        defEn: 'Locking up cryptocurrency to support network operations (like validation) in exchange for rewards.',
        defZh: '锁定加密货币以支持网络运营（如验证），以换取奖励。',
        example: 'You can stake your ETH to earn around 4% annual rewards.',
        exampleZh: '你可以质押 ETH 获得大约 4% 的年化奖励。',
    },
    {
        word: 'Restaking',
        zh: '再质押',
        category: 'defi',
        difficulty: '高级',
        defEn: 'Reusing already-staked assets to secure additional protocols, amplifying capital efficiency.',
        defZh: '将已质押资产在多个协议中重复质押，以获取额外收益并提高资本效率。',
        example: 'EigenLayer pioneered restaking by allowing staked ETH to secure other services.',
        exampleZh: 'EigenLayer 开创了再质押模式，允许已质押的 ETH 为其他服务提供安全保障。',
    },
    {
        word: 'RWA',
        zh: '真实世界资产',
        category: 'defi',
        difficulty: '中级',
        defEn: 'Real World Assets — tokenized representations of physical assets like real estate, bonds, or commodities on the blockchain.',
        defZh: 'Real World Assets — 将房产、债券、大宗商品等现实世界资产代币化后上链。',
        example: 'RWA protocols are bringing US Treasury bonds on-chain.',
        exampleZh: 'RWA 协议正在将美国国债搬上链。',
    },
    {
        word: 'Impermanent Loss',
        zh: '无常损失',
        category: 'defi',
        difficulty: '高级',
        defEn: 'The temporary loss of value experienced by liquidity providers when the price ratio of paired tokens changes.',
        defZh: '流动性提供者因配对代币价格比率变化而遭受的暂时性价值损失。',
        example: 'If ETH price doubles, LPs face impermanent loss compared to simply holding.',
        exampleZh: '如果 ETH 价格翻倍，LP 相比单纯持有会面临无常损失。',
    },
    {
        word: 'Flash Loan',
        zh: '闪电贷',
        category: 'defi',
        difficulty: '高级',
        defEn: 'An uncollateralized loan that must be borrowed and repaid within a single blockchain transaction.',
        defZh: '一种无需抵押的贷款，必须在同一笔区块链交易中借入和归还。',
        example: 'Arbitrageurs use flash loans to exploit price differences across DEXes.',
        exampleZh: '套利者利用闪电贷来利用不同 DEX 之间的价格差异。',
    },
    {
        word: 'TVL',
        zh: '总锁仓量',
        category: 'defi',
        difficulty: '初级',
        defEn: 'Total Value Locked — the total amount of crypto assets deposited in a DeFi protocol.',
        defZh: 'Total Value Locked — 存入 DeFi 协议中的加密资产总价值。',
        example: 'Aave\'s TVL exceeded $10 billion, making it one of the largest DeFi protocols.',
        exampleZh: 'Aave 的 TVL 超过 100 亿美元，使其成为最大的 DeFi 协议之一。',
    },
    {
        word: 'AMM',
        zh: '自动做市商',
        category: 'defi',
        difficulty: '中级',
        defEn: 'Automated Market Maker — an algorithm that automatically sets prices and enables trading through liquidity pools instead of order books.',
        defZh: '自动做市商 — 一种通过流动性池而非订单簿自动定价和促成交易的算法。',
        example: 'Uniswap uses a constant product AMM formula: x * y = k.',
        exampleZh: 'Uniswap 使用恒定乘积 AMM 公式：x * y = k。',
    },

    // ===== NFT =====
    {
        word: 'NFT',
        zh: '非同质化代币',
        category: 'nft',
        difficulty: '初级',
        defEn: 'Non-Fungible Token — a unique digital asset on the blockchain that represents ownership of items like art, music, or collectibles.',
        defZh: '非同质化代币 — 区块链上的唯一数字资产，代表艺术品、音乐或收藏品等的所有权。',
        example: 'He sold his digital artwork as an NFT for 10 ETH.',
        exampleZh: '他将自己的数字艺术作品作为 NFT 以 10 ETH 的价格出售。',
    },
    {
        word: 'Mint',
        zh: '铸造',
        category: 'nft',
        difficulty: '初级',
        defEn: 'The process of creating a new token or NFT on the blockchain for the first time.',
        defZh: '在区块链上首次创建新代币或 NFT 的过程。',
        example: 'The NFT collection will mint on Ethereum next Monday.',
        exampleZh: '该 NFT 系列将于下周一在以太坊上铸造。',
    },
    {
        word: 'Floor Price',
        zh: '地板价',
        category: 'nft',
        difficulty: '初级',
        defEn: 'The lowest price at which an NFT from a collection is listed for sale.',
        defZh: '一个 NFT 系列中挂出的最低售价。',
        example: 'The floor price of Bored Apes dropped to 30 ETH.',
        exampleZh: '无聊猿的地板价跌至 30 ETH。',
    },
    {
        word: 'PFP',
        zh: '头像类 NFT',
        category: 'nft',
        difficulty: '初级',
        defEn: 'Profile Picture — NFTs designed to be used as social media avatars, typically part of a generative collection.',
        defZh: 'Profile Picture — 设计用作社交媒体头像的 NFT，通常是生成式系列的一部分。',
        example: 'CryptoPunks are the OG PFP project in the NFT space.',
        exampleZh: 'CryptoPunks 是 NFT 领域的元祖 PFP 项目。',
    },
    {
        word: 'Airdrop',
        zh: '空投',
        category: 'nft',
        difficulty: '初级',
        defEn: 'Free distribution of tokens or NFTs to wallet addresses, usually as a marketing strategy or reward.',
        defZh: '向钱包地址免费分发代币或 NFT，通常作为营销策略或奖励。',
        example: 'Uniswap airdropped 400 UNI tokens to every early user.',
        exampleZh: 'Uniswap 向每位早期用户空投了 400 个 UNI 代币。',
    },

    // ===== Layer 2 =====
    {
        word: 'Layer 2',
        zh: '二层网络',
        category: 'layer2',
        difficulty: '中级',
        defEn: 'A secondary framework built on top of a blockchain (Layer 1) to improve scalability and reduce transaction costs.',
        defZh: '构建在区块链（一层网络）之上的二级框架，用于提高可扩展性和降低交易成本。',
        example: 'Arbitrum and Optimism are popular Ethereum Layer 2 solutions.',
        exampleZh: 'Arbitrum 和 Optimism 是流行的以太坊 Layer 2 解决方案。',
    },
    {
        word: 'Rollup',
        zh: '卷叠',
        category: 'layer2',
        difficulty: '高级',
        defEn: 'A Layer 2 scaling technique that bundles multiple transactions off-chain and submits them to the main chain as a single batch.',
        defZh: '一种 Layer 2 扩容技术，将多笔交易在链下打包后作为单笔批量提交到主链。',
        example: 'Optimistic rollups assume transactions are valid unless challenged.',
        exampleZh: '乐观卷叠假设交易是有效的，除非被质疑。',
    },
    {
        word: 'ZK Proof',
        zh: '零知识证明',
        category: 'layer2',
        difficulty: '高级',
        defEn: 'Zero-Knowledge Proof — a cryptographic method to prove something is true without revealing the underlying data.',
        defZh: '零知识证明 — 一种密码学方法，在不泄露底层数据的情况下证明某事为真。',
        example: 'ZK rollups use zero-knowledge proofs to validate transactions off-chain.',
        exampleZh: 'ZK 卷叠使用零知识证明在链下验证交易。',
    },
    {
        word: 'Gas Fee',
        zh: 'Gas 费 / 矿工费',
        category: 'layer2',
        difficulty: '初级',
        defEn: 'The fee paid to process and validate transactions on a blockchain network.',
        defZh: '在区块链网络上处理和验证交易所支付的费用。',
        example: 'Ethereum gas fees can spike during periods of high network activity.',
        exampleZh: '以太坊 Gas 费在网络活动高峰期可能会飙升。',
    },
    {
        word: 'Sharding',
        zh: '分片',
        category: 'layer2',
        difficulty: '高级',
        defEn: 'A database partitioning technique applied to blockchains, splitting the network into smaller pieces to process transactions in parallel.',
        defZh: '一种应用于区块链的数据库分区技术，将网络拆分为更小的片段以并行处理交易。',
        example: 'Ethereum\'s roadmap includes sharding to dramatically increase throughput.',
        exampleZh: '以太坊路线图包括分片以大幅提高吞吐量。',
    },

    // ===== 共识 / 安全 =====
    {
        word: 'Consensus Mechanism',
        zh: '共识机制',
        category: 'consensus',
        difficulty: '中级',
        defEn: 'The process by which a blockchain network agrees on the current state of the ledger (e.g., Proof of Work, Proof of Stake).',
        defZh: '区块链网络就账本当前状态达成一致的过程（如工作量证明、权益证明）。',
        example: 'Ethereum switched from Proof of Work to Proof of Stake in The Merge.',
        exampleZh: '以太坊在 The Merge 中从工作量证明切换到了权益证明。',
    },
    {
        word: 'PoS',
        zh: '权益证明',
        category: 'consensus',
        difficulty: '中级',
        defEn: 'Proof of Stake — a consensus mechanism where validators are chosen based on the amount of cryptocurrency they stake.',
        defZh: '权益证明 — 根据验证者质押的加密货币数量来选择验证者的共识机制。',
        example: 'PoS is more energy-efficient than PoW since it doesn\'t require mining.',
        exampleZh: 'PoS 比 PoW 更节能，因为它不需要挖矿。',
    },
    {
        word: 'PoW',
        zh: '工作量证明',
        category: 'consensus',
        difficulty: '中级',
        defEn: 'Proof of Work — a consensus mechanism where miners solve complex mathematical puzzles to validate transactions.',
        defZh: '工作量证明 — 矿工通过解决复杂数学难题来验证交易的共识机制。',
        example: 'Bitcoin still uses PoW, which requires significant computational power.',
        exampleZh: 'Bitcoin 仍然使用 PoW，这需要大量的计算能力。',
    },
    {
        word: 'Smart Contract',
        zh: '智能合约',
        category: 'consensus',
        difficulty: '初级',
        defEn: 'Self-executing code deployed on a blockchain that automatically enforces the terms of an agreement.',
        defZh: '部署在区块链上的自动执行代码，自动执行协议条款。',
        example: 'The lending protocol uses smart contracts to manage collateral automatically.',
        exampleZh: '借贷协议使用智能合约自动管理抵押品。',
    },
    {
        word: 'Oracle',
        zh: '预言机',
        category: 'consensus',
        difficulty: '中级',
        defEn: 'A service that provides external real-world data to smart contracts on the blockchain.',
        defZh: '为区块链上的智能合约提供外部真实世界数据的服务。',
        example: 'Chainlink is the most widely used oracle network in DeFi.',
        exampleZh: 'Chainlink 是 DeFi 中使用最广泛的预言机网络。',
    },
    {
        word: 'MEV',
        zh: '最大可提取价值',
        category: 'consensus',
        difficulty: '高级',
        defEn: 'Maximal Extractable Value — the profit validators can make by reordering, inserting, or censoring transactions in a block.',
        defZh: '最大可提取价值 — 验证者通过重新排序、插入或审查区块中的交易所能获得的利润。',
        example: 'MEV bots front-run DEX trades to capture arbitrage profits.',
        exampleZh: 'MEV 机器人抢跑 DEX 交易以捕获套利利润。',
    },

    // ===== 交易 / 市场 =====
    {
        word: 'HODL',
        zh: '长期持有',
        category: 'trading',
        difficulty: '初级',
        defEn: 'A misspelling of "hold" that became crypto slang for holding assets long-term regardless of price volatility.',
        defZh: '"hold" 的拼写错误，后成为加密圈术语，指无论价格波动都长期持有资产。',
        example: 'True believers HODL through bear markets.',
        exampleZh: '真正的信仰者在熊市中也会 HODL。',
    },
    {
        word: 'DYOR',
        zh: '自己做研究',
        category: 'trading',
        difficulty: '初级',
        defEn: 'Do Your Own Research — a reminder to investigate before investing, rather than following hype or others\' advice.',
        defZh: 'Do Your Own Research — 提醒投资前自行调研，而非盲目跟风或听从他人建议。',
        example: 'This is not financial advice — always DYOR before buying any token.',
        exampleZh: '这不是投资建议 — 购买任何代币前请务必 DYOR。',
    },
    {
        word: 'Whale',
        zh: '巨鲸',
        category: 'trading',
        difficulty: '初级',
        defEn: 'An individual or entity that holds a very large amount of cryptocurrency, enough to influence market prices.',
        defZh: '持有大量加密货币的个人或实体，足以影响市场价格。',
        example: 'A whale just moved 10,000 BTC to an exchange — could signal a sell-off.',
        exampleZh: '一头巨鲸刚刚将 10,000 BTC 转入交易所 — 可能预示着抛售。',
    },
    {
        word: 'FUD',
        zh: '恐惧、不确定、怀疑',
        category: 'trading',
        difficulty: '初级',
        defEn: 'Fear, Uncertainty, and Doubt — negative information or sentiment spread to discourage investment.',
        defZh: 'Fear, Uncertainty, and Doubt — 散布负面信息或情绪以打击投资信心。',
        example: 'Don\'t let FUD influence your investment decisions.',
        exampleZh: '不要让 FUD 影响你的投资决策。',
    },
    {
        word: 'Bull / Bear Market',
        zh: '牛市 / 熊市',
        category: 'trading',
        difficulty: '初级',
        defEn: 'Bull market means rising prices and optimism; bear market means falling prices and pessimism.',
        defZh: '牛市指价格上涨和乐观情绪；熊市指价格下跌和悲观情绪。',
        example: 'We\'re entering a bull market — Bitcoin just broke its all-time high.',
        exampleZh: '我们正在进入牛市 — Bitcoin 刚刚突破了历史最高价。',
    },
    {
        word: 'DEX',
        zh: '去中心化交易所',
        category: 'trading',
        difficulty: '中级',
        defEn: 'Decentralized Exchange — a peer-to-peer marketplace for trading crypto without a central authority.',
        defZh: '去中心化交易所 — 无需中心化机构的点对点加密货币交易市场。',
        example: 'Uniswap is the largest DEX by trading volume on Ethereum.',
        exampleZh: 'Uniswap 是以太坊上交易量最大的 DEX。',
    },
    {
        word: 'Slippage',
        zh: '滑点',
        category: 'trading',
        difficulty: '中级',
        defEn: 'The difference between the expected price of a trade and the actual price at which it executes.',
        defZh: '交易的预期价格与实际成交价格之间的差异。',
        example: 'Set your slippage tolerance to 0.5% to avoid front-running.',
        exampleZh: '将滑点容差设置为 0.5% 以避免被抢跑。',
    },

    // ===== 基础设施 =====
    {
        word: 'Blockchain',
        zh: '区块链',
        category: 'infra',
        difficulty: '初级',
        defEn: 'A distributed, immutable digital ledger that records transactions across a network of computers.',
        defZh: '一种分布式、不可篡改的数字账本，记录跨计算机网络的交易。',
        example: 'Every Bitcoin transaction is permanently recorded on the blockchain.',
        exampleZh: '每笔 Bitcoin 交易都被永久记录在区块链上。',
    },
    {
        word: 'Wallet',
        zh: '钱包',
        category: 'infra',
        difficulty: '初级',
        defEn: 'A software or hardware tool used to store, send, and receive cryptocurrency by managing private keys.',
        defZh: '通过管理私钥来存储、发送和接收加密货币的软件或硬件工具。',
        example: 'MetaMask is the most popular browser-based crypto wallet.',
        exampleZh: 'MetaMask 是最流行的浏览器端加密钱包。',
    },
    {
        word: 'Private Key',
        zh: '私钥',
        category: 'infra',
        difficulty: '初级',
        defEn: 'A secret cryptographic key that gives the holder full control over their cryptocurrency. Never share it.',
        defZh: '一个秘密加密密钥，赋予持有者对其加密货币的完全控制权。永远不要分享它。',
        example: 'Not your keys, not your coins — always protect your private key.',
        exampleZh: '不是你的密钥，就不是你的币 — 务必保护好你的私钥。',
    },
    {
        word: 'DApp',
        zh: '去中心化应用',
        category: 'infra',
        difficulty: '中级',
        defEn: 'Decentralized Application — an application running on a blockchain network rather than centralized servers.',
        defZh: '去中心化应用 — 运行在区块链网络上而非中心化服务器上的应用程序。',
        example: 'Ethereum hosts thousands of DApps across DeFi, gaming, and social.',
        exampleZh: '以太坊上有数千个横跨 DeFi、游戏和社交领域的 DApp。',
    },
    {
        word: 'Cross-chain',
        zh: '跨链',
        category: 'infra',
        difficulty: '中级',
        defEn: 'Technology enabling the transfer of assets and data between different blockchain networks.',
        defZh: '使不同区块链网络之间能够传输资产和数据的技术。',
        example: 'Cross-chain bridges let you move tokens from Ethereum to Solana.',
        exampleZh: '跨链桥让你可以将代币从以太坊转移到 Solana。',
    },
    {
        word: 'Account Abstraction',
        zh: '账户抽象',
        category: 'infra',
        difficulty: '高级',
        defEn: 'A blockchain upgrade that makes wallets programmable, enabling features like social recovery, gas sponsorship, and batch transactions.',
        defZh: '一种区块链升级，使钱包可编程，支持社交恢复、Gas 代付和批量交易等功能。',
        example: 'Account abstraction (ERC-4337) makes crypto wallets as easy as email login.',
        exampleZh: '账户抽象（ERC-4337）使加密钱包像邮箱登录一样简单。',
    },

    // ===== Web3 / DAO =====
    {
        word: 'Web3',
        zh: 'Web3',
        category: 'web3',
        difficulty: '初级',
        defEn: 'The next evolution of the internet built on decentralized technologies, giving users ownership over their data and digital assets.',
        defZh: '基于去中心化技术的下一代互联网，赋予用户对数据和数字资产的所有权。',
        example: 'Web3 aims to replace platform monopolies with user-owned protocols.',
        exampleZh: 'Web3 旨在用用户拥有的协议取代平台垄断。',
    },
    {
        word: 'DAO',
        zh: '去中心化自治组织',
        category: 'web3',
        difficulty: '中级',
        defEn: 'Decentralized Autonomous Organization — a community-led entity governed by smart contracts and token holder votes.',
        defZh: '去中心化自治组织 — 由智能合约和代币持有者投票治理的社区主导实体。',
        example: 'MakerDAO lets MKR holders vote on protocol changes.',
        exampleZh: 'MakerDAO 让 MKR 持有者对协议变更进行投票。',
    },
    {
        word: 'Governance Token',
        zh: '治理代币',
        category: 'web3',
        difficulty: '中级',
        defEn: 'A token that grants holders voting rights on protocol decisions, such as fee structures or upgrades.',
        defZh: '赋予持有者对协议决策（如费用结构或升级）投票权的代币。',
        example: 'UNI holders can vote on how Uniswap\'s treasury is spent.',
        exampleZh: 'UNI 持有者可以对 Uniswap 国库如何使用进行投票。',
    },
    {
        word: 'Tokenomics',
        zh: '代币经济学',
        category: 'web3',
        difficulty: '中级',
        defEn: 'The economic design of a cryptocurrency — supply, distribution, utility, and incentive mechanisms.',
        defZh: '加密货币的经济设计 — 供应、分配、用途和激励机制。',
        example: 'Good tokenomics align the incentives of users, developers, and investors.',
        exampleZh: '良好的代币经济学能对齐用户、开发者和投资者的激励。',
    },
    {
        word: 'SBT',
        zh: '灵魂绑定代币',
        category: 'web3',
        difficulty: '高级',
        defEn: 'Soulbound Token — a non-transferable NFT representing credentials, achievements, or identity on-chain.',
        defZh: '灵魂绑定代币 — 一种不可转让的 NFT，代表链上的资质、成就或身份。',
        example: 'Universities could issue diplomas as SBTs to prevent credential fraud.',
        exampleZh: '大学可以将文凭作为 SBT 发行，以防止学历造假。',
    },
    {
        word: 'DID',
        zh: '去中心化身份',
        category: 'web3',
        difficulty: '高级',
        defEn: 'Decentralized Identifier — a self-sovereign digital identity system where users control their own identity data.',
        defZh: '去中心化标识符 — 一种自主主权的数字身份系统，用户控制自己的身份数据。',
        example: 'DID allows you to log in to DApps without sharing personal data with third parties.',
        exampleZh: 'DID 允许你在不向第三方分享个人数据的情况下登录 DApp。',
    },

    // ===== 圈内黑话 =====
    {
        word: 'LFG',
        zh: '冲！/ 干就完了',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Let\'s F***ing Go — an expression of extreme excitement and enthusiasm, often used when a project launches or price surges.',
        defZh: 'Let\'s F***ing Go — 表达极度兴奋和热情的口号，常在项目上线或价格飙升时使用。',
        example: 'Bitcoin just hit $100K — LFG!',
        exampleZh: 'Bitcoin 刚突破 10 万美元 — LFG！冲！',
    },
    {
        word: 'Bullish',
        zh: '看涨 / 看好',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Having a positive, optimistic outlook on a cryptocurrency or the market in general.',
        defZh: '对某种加密货币或整体市场持积极、乐观的看法。',
        example: 'I\'m super bullish on Ethereum after the latest upgrade.',
        exampleZh: '在最新升级之后，我非常看好以太坊。',
    },
    {
        word: 'Bearish',
        zh: '看跌 / 看衰',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Having a negative, pessimistic outlook expecting prices to decline.',
        defZh: '持消极、悲观的看法，预期价格将下跌。',
        example: 'The market sentiment turned bearish after the regulatory crackdown.',
        exampleZh: '在监管打击之后，市场情绪转为看跌。',
    },
    {
        word: 'To the Moon',
        zh: '涨上天 / 登月',
        category: 'slang',
        difficulty: '初级',
        defEn: 'A phrase indicating belief that a cryptocurrency\'s price will rise dramatically.',
        defZh: '表示相信某种加密货币价格将大幅上涨的短语。',
        example: 'Diamond hands and HODL — this coin is going to the moon!',
        exampleZh: '钻石手加 HODL — 这个币要涨上天了！',
    },
    {
        word: 'WAGMI',
        zh: '我们都会成功的',
        category: 'slang',
        difficulty: '初级',
        defEn: 'We\'re All Gonna Make It — a rallying cry expressing collective optimism in the crypto community.',
        defZh: 'We\'re All Gonna Make It — 加密社区中表达集体乐观精神的口号。',
        example: 'The community kept shouting WAGMI even during the crash.',
        exampleZh: '即使在暴跌期间，社区仍在高喊 WAGMI。',
    },
    {
        word: 'NGMI',
        zh: '没戏了',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Not Gonna Make It — used to express that someone is making a bad decision or will fail.',
        defZh: 'Not Gonna Make It — 用来表示某人做了错误决定或将会失败。',
        example: 'Selling your ETH at the bottom? NGMI.',
        exampleZh: '在底部卖掉 ETH？NGMI，没戏了。',
    },
    {
        word: 'Rug Pull',
        zh: '跑路 / 卷款',
        category: 'slang',
        difficulty: '中级',
        defEn: 'A scam where developers abandon a project and run away with investors\' funds.',
        defZh: '开发者放弃项目并携投资者资金跑路的骗局。',
        example: 'The DeFi project turned out to be a rug pull — $2 million vanished overnight.',
        exampleZh: '这个 DeFi 项目原来是跑路骗局 — 200 万美元一夜之间消失。',
    },
    {
        word: 'Pump and Dump',
        zh: '拉盘砸盘',
        category: 'slang',
        difficulty: '中级',
        defEn: 'A scheme to artificially inflate a token\'s price through hype, then sell at the peak, crashing the price.',
        defZh: '通过炒作人为抬高代币价格，然后在高点抛售，导致价格暴跌的骗局。',
        example: 'That meme coin was a classic pump and dump — early buyers got rekt.',
        exampleZh: '那个 meme 币是经典的拉盘砸盘 — 后来的买家全亏了。',
    },
    {
        word: 'Diamond Hands',
        zh: '钻石手',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Someone who holds their position firmly regardless of market volatility or losses.',
        defZh: '无论市场波动或亏损都坚定持仓的人。',
        example: 'Diamond hands don\'t panic sell — they hold through the dip.',
        exampleZh: '钻石手不会恐慌抛售 — 他们在下跌中坚定持有。',
    },
    {
        word: 'Paper Hands',
        zh: '纸手',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Someone who sells too quickly out of fear, often at a loss.',
        defZh: '因恐惧而过早卖出的人，通常会亏损。',
        example: 'Paper hands sold at the dip and missed the 5x rally.',
        exampleZh: '纸手在下跌时卖出，错过了 5 倍涨幅。',
    },
    {
        word: 'Ape In',
        zh: '冲进去 / 无脑买入',
        category: 'slang',
        difficulty: '初级',
        defEn: 'To invest in a token impulsively without doing proper research, driven by FOMO.',
        defZh: '在没有充分研究的情况下因 FOMO 冲动买入某个代币。',
        example: 'I aped into that new memecoin and somehow made 10x.',
        exampleZh: '我无脑冲进了那个新 meme 币，居然赚了 10 倍。',
    },
    {
        word: 'Rekt',
        zh: '亏惨了 / 爆了',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Slang for "wrecked" — suffering a severe financial loss, often from liquidation or a bad trade.',
        defZh: '"wrecked" 的变体拼写 — 遭受严重财务损失，通常因爆仓或失败的交易。',
        example: 'He went 100x leverage long and got completely rekt.',
        exampleZh: '他做了 100 倍杠杆做多，结果彻底爆仓了。',
    },
    {
        word: 'GM / GN',
        zh: '早安 / 晚安',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Good Morning / Good Night — crypto community greetings used on social media to show camaraderie.',
        defZh: 'Good Morning / Good Night — 加密社区在社交媒体上的问候语，用以表达社区凝聚力。',
        example: 'GM frens! Another day in the trenches.',
        exampleZh: 'GM 朋友们！又是在战壕里的一天。',
    },
    {
        word: 'Alpha',
        zh: 'Alpha / 内幕消息',
        category: 'slang',
        difficulty: '中级',
        defEn: 'Exclusive, valuable information or insights that give an edge in investing or trading.',
        defZh: '独家的、有价值的信息或洞察，能在投资或交易中获得优势。',
        example: 'This newsletter drops alpha on undervalued DeFi projects every week.',
        exampleZh: '这个 newsletter 每周都会分享被低估的 DeFi 项目的 Alpha。',
    },
    {
        word: 'Bag Holder',
        zh: '接盘侠',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Someone left holding a token that has significantly dropped in value after others have sold.',
        defZh: '在其他人已经卖出后，仍然持有已大幅贬值代币的人。',
        example: 'After the crash, he became a bag holder with thousands of worthless tokens.',
        exampleZh: '暴跌之后，他成了接盘侠，持有数千个一文不值的代币。',
    },
    {
        word: 'Shill',
        zh: '喊单 / 推销',
        category: 'slang',
        difficulty: '中级',
        defEn: 'To aggressively promote a cryptocurrency, often for personal gain.',
        defZh: '大力推广某种加密货币，通常是为了个人利益。',
        example: 'Influencers who shill random altcoins are often getting paid to do it.',
        exampleZh: '那些喊单随机山寨币的 KOL 通常是收了钱才这么做的。',
    },
    {
        word: 'Fren',
        zh: '朋友 / 伙伴',
        category: 'slang',
        difficulty: '初级',
        defEn: 'A deliberate misspelling of "friend" used in crypto and Web3 communities.',
        defZh: '"friend" 的故意拼写变体，在加密和 Web3 社区中使用。',
        example: 'GM frens, hope you\'re all having a green day!',
        exampleZh: 'GM 伙计们，希望大家今天都是绿色的（涨的）！',
    },
    {
        word: 'Maxi',
        zh: '极端主义者',
        category: 'slang',
        difficulty: '中级',
        defEn: 'Short for "maximalist" — someone who believes only one blockchain (usually Bitcoin) matters.',
        defZh: '"maximalist" 的缩写 — 相信只有一条链（通常是 Bitcoin）才有价值的人。',
        example: 'Bitcoin maxis think every altcoin is a scam.',
        exampleZh: 'Bitcoin 极端主义者认为所有山寨币都是骗局。',
    },
    {
        word: 'Degen',
        zh: '赌狗 / 梭哈玩家',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Short for "degenerate" — a trader who takes extreme risks, often in memecoins or high-leverage trades.',
        defZh: '"degenerate" 的缩写 — 承担极端风险的交易者，通常玩 meme 币或高杠杆交易。',
        example: 'Full degen mode: I just put my rent money into a memecoin.',
        exampleZh: '完全赌狗模式：我刚把房租钱投进了一个 meme 币。',
    },
    {
        word: 'No-coiner',
        zh: '无币者',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Someone who does not own any cryptocurrency, often used dismissively by crypto enthusiasts.',
        defZh: '不持有任何加密货币的人，通常被加密爱好者用来调侃。',
        example: 'My friend is still a no-coiner — he thinks crypto is all a bubble.',
        exampleZh: '我朋友还是个无币者 — 他认为加密货币全是泡沫。',
    },
    {
        word: 'FOMO',
        zh: '错失恐惧症',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Fear Of Missing Out — the anxiety of missing a profitable opportunity, causing impulsive buying.',
        defZh: 'Fear Of Missing Out — 害怕错过盈利机会的焦虑，导致冲动购买。',
        example: 'I bought the top because of FOMO and now I\'m down 50%.',
        exampleZh: '我因为 FOMO 在高点买入，现在亏了 50%。',
    },
    {
        word: 'Memecoin',
        zh: 'Meme 币',
        category: 'slang',
        difficulty: '初级',
        defEn: 'A cryptocurrency created as a joke or based on internet memes, with value driven by community hype rather than utility.',
        defZh: '作为玩笑或基于网络梗创建的加密货币，价值由社区炒作而非实用性驱动。',
        example: 'Dogecoin started as a memecoin but became a top 10 crypto.',
        exampleZh: 'Dogecoin 最初是 meme 币，但后来成为了前十大加密货币。',
    },
    {
        word: 'Altcoin',
        zh: '山寨币 / 替代币',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Any cryptocurrency other than Bitcoin. Short for "alternative coin."',
        defZh: '除 Bitcoin 以外的任何加密货币。"alternative coin" 的缩写。',
        example: 'During altcoin season, smaller coins often outperform Bitcoin.',
        exampleZh: '在山寨币季节，小币种通常表现优于 Bitcoin。',
    },
    {
        word: 'Flippening',
        zh: '大翻转',
        category: 'slang',
        difficulty: '中级',
        defEn: 'A hypothetical event where Ethereum\'s market cap surpasses Bitcoin\'s.',
        defZh: '以太坊市值超过 Bitcoin 市值的假想事件。',
        example: 'ETH maxis have been predicting the flippening for years.',
        exampleZh: 'ETH 极端主义者多年来一直在预测大翻转。',
    },
    {
        word: 'NFA',
        zh: '非投资建议',
        category: 'slang',
        difficulty: '初级',
        defEn: 'Not Financial Advice — a disclaimer used when sharing opinions about investments.',
        defZh: 'Not Financial Advice — 分享投资观点时使用的免责声明。',
        example: 'I think SOL will hit $500 this cycle, but NFA.',
        exampleZh: '我觉得 SOL 这轮能到 500 美元，但 NFA，非投资建议。',
    },
];
